/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniadvancedemo_JniUse_Struct */

#ifndef _Included_com_example_jniadvancedemo_JniUse_Struct
#define _Included_com_example_jniadvancedemo_JniUse_Struct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    StructToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_StructToString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    StructToDefind
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_StructToDefind
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    StructToNest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_StructToNest
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    StructMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_StructMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    StructSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_StructSize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_Struct
 * Method:    unionToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_Struct_unionToString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
