/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniadvancedemo_JniUse_TestJni */

#ifndef _Included_com_example_jniadvancedemo_JniUse_TestJni
#define _Included_com_example_jniadvancedemo_JniUse_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    stringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_stringFromJNI2
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    getEmployee
 * Signature: (Ljava/lang/String;D)Lcom/example/jniadvancedemo/JniUse/Employee;
 */
JNIEXPORT jobject JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_getEmployee
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    employeePrint
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_employeePrint
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    bastTypeLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_bastTypeLog
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    random
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_random
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    clloc
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_clloc
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    cllocSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_cllocSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    compress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_compress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    charTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_charTest
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    charLength
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_charLength
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    charChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_charChange
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jniadvancedemo_JniUse_TestJni
 * Method:    charEquals
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_jniadvancedemo_JniUse_TestJni_charEquals
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
